version: '3'

services:
    #Postgres Service
    db-postgres:
        image: postgres
        container_name: postgres-kanastra
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: kanastra
            POSTGRES_PASSWORD: mcrroot
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./db_script/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network-kanastra
    
    #Redis Service
    redis:
        image: redis:4.0
        container_name: redis-kanastra
        ports:
            - "6382:6379"
        networks:
            - app-network-kanastra
    
    #PHP Service
    app:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        image: laravel_php
        container_name: app-kanastra
        restart: unless-stopped
        depends_on:
            - db-postgres
        tty: true
        environment:
            SERVICE_NAME: app-kanastra
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./www:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network-kanastra

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver-kanastra
        restart: unless-stopped
        depends_on:
            - db-postgres
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./www:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network-kanastra

    #MongDB Service
    mongo:
        image: mongo:5.0
        container_name: mongo-kanastra
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=MongoDB2024!
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - ./mongodb:/data/db
        command: [--auth]
        networks:
            - app-network-kanastra

    mongo-express:
        image: mongo-express
        container_name: mexpress-kanastra
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=MongoDB2024!
            - ME_CONFIG_MONGODB_URL=mongodb://root:MongoDB2024!@mongo:27017/?authSource=admin
            - ME_CONFIG_BASICAUTH_USERNAME=mexpress
            - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
        links:
            - mongo
        restart: unless-stopped
        ports:
            - "8081:8081"
        networks:
            - app-network-kanastra

    supervisor01:
        image: laravel_php
        container_name: app-supervisor-kanastra-01
        volumes:
            - ./www:/var/www
        networks:
            - app-network-kanastra
        depends_on:
            - app
            - webserver
        command: supervisord

#Docker Networks
networks:
    app-network-kanastra:
        driver: bridge

#Volumes
volumes:
    dbdata-kanastra:
        driver: local
    postgresql:
    postgresql_data:
